# Generated by Django 4.1.1 on 2023-10-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upazila',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='upazila',
            name='long',
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
