# Generated by Django 4.1.1 on 2023-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0003_alter_upazila_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
