# Generated by Django 4.1.1 on 2023-10-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0004_alter_upazila_name_alter_upazila_name_bn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upazila',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='upazila',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
