# Generated by Django 4.1.1 on 2023-10-22 10:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0005_alter_upazila_name_alter_upazila_name_bn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name_bn', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bangladesh.upazila')),
            ],
        ),
    ]
