# Generated by Django 4.1.1 on 2023-10-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bangladesh', '0006_union'),
    ]

    operations = [
        migrations.AlterField(
            model_name='union',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='union',
            name='name_bn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
